; PlatformIO Project Configuration File
; 工程实践循迹小车 — 电控部分
; 目标板: Robot Mboard KR-duino V1.5 (兼容 Arduino Uno R3)

[env:KRduino]
platform = atmelavr
board = uno
framework = arduino

; 串口波特率
monitor_speed = 115200

; 编译器优化
build_flags =
    -Os

; 依赖库
lib_deps =
    Servo
